name: tiktok_tutorial
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  get: ^4.6.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  timeago: ^3.1.0
  video_compress: ^3.1.0
  video_player: ^2.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true